# Generated by Django 3.2 on 2023-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0002_customuser_invited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
