# Generated by Django 3.2 on 2023-08-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0004_customuser_referred_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteCode',
        ),
    ]
