# Generated by Django 3.2 on 2023-08-18 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0005_delete_invitecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_phones',
            field=models.ManyToManyField(blank=True, related_name='_referral_app_customuser_referred_phones_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
